# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7BgtJm7N9prVa5MQjBUpP_bK65eXRVG
"""

gpa = float(input("nhập điểm trung bình (GPA): "))
if gpa >= 8.5:
    print("xếp loại: xuất sắc")
elif gpa >= 7.0:
    print("xếp loại: giỏi")
elif gpa >= 5.5:
    print("xếp loại: khá")
elif gpa >= 4.0:
    print("xếp loại: trung bình")
else:
    print("xếp loại: yếu")

n = int(input("nhập số nguyên dương n: "))
tong = 0
for i in range(2, n + 1, 2):
    tong += i
print(f"tổng các số chẵn từ 1 đến {n} là: {tong}")

mat_khau_dung = "python123"
so_lan_thu = 3

for i in range(so_lan_thu):
    nhap = input(f"mời nhập mật khẩu (Lần {i+1}): ")

    if nhap == mat_khau_dung:
        print("đăng nhập thành công")
        break
else:
    print("tài khoản bị khóa")